SELECT SYMBOL, TRADE_DATE, VOLUME
FROM STOCK_PRICES
ORDER BY VOLUME DESC
LIMIT 5;

-- 7 day moving average
SELECT 
    TRADE_DATE,
    CLOSE_PRICE,
    AVG(CLOSE_PRICE) OVER (
        ORDER BY TRADE_DATE 
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS MOVING_AVG_7DAY
FROM STOCK_PRICES
WHERE SYMBOL = 'AAPL'
ORDER BY TRADE_DATE DESC;

--biggest single day price change
SELECT 
    TRADE_DATE,
    OPEN_PRICE,
    CLOSE_PRICE,
    ROUND(CLOSE_PRICE - OPEN_PRICE, 2) AS PRICE_CHANGE,
    ROUND(((CLOSE_PRICE - OPEN_PRICE) / OPEN_PRICE) * 100, 2) AS PERCENT_CHANGE
FROM STOCK_PRICES
WHERE SYMBOL = 'AAPL'
ORDER BY ABS(PRICE_CHANGE) DESC
LIMIT 5;